name: Sync Datasets to GitHub and Supabase Storage

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Run Make
        run: make

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "actions@users.noreply.github.com"
          git add -A
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit"
          else
            git commit -m "Update data"
            git push
          fi

      - name: Sync Data to Supabase Storage
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          DATASET_TYPE: free
        run: |
          pip install supabase
          python scripts/sync_to_supabase.py
